'use client';

import { useEffect, useState } from 'react';
import { Button } from '@/components/ui/button';
import { Dialog, DialogContent, DialogDescription, DialogHeader, DialogTitle } from '@/components/ui/dialog';
import type { ChatHistoryItem } from '@/lib/chats/history';

type HistoryChat = { id:string; name:string; link:string };
const eventNames:Record<string,string>={chat_state_changed:'Зміна стану',chat_joined:'Приєднання',publication:'Публікація',chat_profile_changed:'Профіль оновлено'};
const actionNames:Record<string,string>={joined:'Приєднано',waiting:'Очікування запрошення',approved:'Запрошення підтверджено',failed:'Невдале приєднання',archive:'Перенесено в архів',restore:'Відновлено',return_to_join:'Повернуто для приєднання',assign_account:'Перепризначено акаунт',confirm_leave:'Вихід із чату підтверджено',undo_leave:'Підтвердження виходу скасовано',rename:'Чат перейменовано'};

export function ChatHistoryDialog({open,chat,onClose,finalFocus}:{open:boolean;chat:HistoryChat|null;onClose:()=>void;finalFocus?:()=>HTMLElement|null}) {
  const [events,setEvents]=useState<ChatHistoryItem[]>([]); const [busy,setBusy]=useState(false); const [error,setError]=useState('');
  useEffect(()=>{if(!open||!chat)return;let cancelled=false;queueMicrotask(()=>{if(!cancelled){setEvents([]);setBusy(true);setError('');}});
    fetch(`/api/chats/history?id=${encodeURIComponent(chat.id)}`,{cache:'no-store'}).then(async response=>{const value:unknown=await response.json();if(!response.ok)throw new Error(value&&typeof value==='object'&&'error' in value&&typeof value.error==='string'?value.error:'Не вдалося завантажити історію.');if(!cancelled)setEvents(value&&typeof value==='object'&&Array.isArray((value as {events?:unknown}).events)?(value as {events:ChatHistoryItem[]}).events:[]);}).catch(reason=>{if(!cancelled)setError(reason instanceof Error?reason.message:'Не вдалося завантажити історію.');}).finally(()=>{if(!cancelled)setBusy(false);});
    return()=>{cancelled=true;};
  },[open,chat]);
  return <Dialog open={open} onOpenChange={next=>{if(!next&&!busy)onClose();}}><DialogContent className="chat-history-dialog" showCloseButton={false} finalFocus={finalFocus}><DialogHeader><DialogTitle>Історія чату</DialogTitle><DialogDescription>{chat?.name} · {chat?.link}</DialogDescription></DialogHeader><Button className="chat-history-close" variant="ghost" size="icon" aria-label="Закрити" disabled={busy} onClick={onClose}>×</Button>{error&&<div className="workspace-error" role="alert">{error}</div>}{busy?<p className="workspace-loading">Завантажуємо історію…</p>:events.length?<ol className="chat-history-list">{events.map(event=><li key={event.id}><div><strong>{eventNames[event.eventType]||event.eventType}</strong>{event.eventType==='chat_state_changed'&&typeof event.metadata.action==='string'&&<span> · {actionNames[event.metadata.action]||event.metadata.action}</span>}{event.eventType==='publication'&&event.advertisementTitle&&<small className="chat-history-material"> · {event.advertisementTitle}</small>}{event.eventType==='publication'&&(event.metadata.language==='uk'||event.metadata.language==='ru')&&<small className="chat-history-material"> · {event.metadata.language==='uk'?'UA':'RU'}</small>}</div><time dateTime={new Date(event.occurredAt*1000).toISOString()}>{new Intl.DateTimeFormat('uk-UA',{dateStyle:'medium',timeStyle:'short',timeZone:'Europe/Kyiv'}).format(new Date(event.occurredAt*1000))}</time></li>)}</ol>:<p className="muted-note">Історія ще порожня.</p>}<div className="dialog-actions"><Button variant="outline" onClick={onClose}>Закрити</Button></div></DialogContent></Dialog>;
}