'use client';

import { useCallback, useEffect, useState } from 'react';
import { Archive, BookOpenText, FilePlus2, Search } from 'lucide-react';
import { Badge } from '@/components/ui/badge';
import { Button } from '@/components/ui/button';
import { Input } from '@/components/ui/input';
import { Textarea } from '@/components/ui/textarea';

type Kind = 'advertisement' | 'script';
type Item = { id: string; kind: Kind; title: string; ukText: string; ruText: string; notes: string; tags: string[]; platforms: string[]; updatedAt: number };
const kindLabels: Record<Kind, string> = { advertisement: 'Оголошення', script: 'Скрипт' };

export function LibraryWorkspace() {
  const [kind, setKind] = useState<Kind>('advertisement');
  const [search, setSearch] = useState('');
  const [items, setItems] = useState<Item[]>([]);
  const [selected, setSelected] = useState<Item | null>(null);
  const [form, setForm] = useState({ title: '', ukText: '', ruText: '', notes: '', tags: '', platforms: '' });
  const [loading, setLoading] = useState(true); const [saving, setSaving] = useState(false); const [error, setError] = useState(''); const [notice, setNotice] = useState('');
  const load = useCallback(async () => { setLoading(true); setError(''); try { const response = await fetch(`/api/library?kind=${kind}&search=${encodeURIComponent(search)}`, { cache: 'no-store' }); const body = await response.json() as { items?: Item[]; error?: string }; if (!response.ok) throw new Error(body.error || 'Не вдалося завантажити бібліотеку.'); setItems(body.items || []); } catch (reason) { setError(reason instanceof Error ? reason.message : 'Не вдалося завантажити бібліотеку.'); } finally { setLoading(false); } }, [kind, search]);
  useEffect(() => { const timer = setTimeout(() => void load(), search ? 250 : 0); return () => clearTimeout(timer); }, [load, search]);
  function edit(item: Item | null) { setSelected(item); setForm(item ? { title: item.title, ukText: item.ukText, ruText: item.ruText, notes: item.notes, tags: item.tags.join(', '), platforms: item.platforms.join(', ') } : { title: '', ukText: '', ruText: '', notes: '', tags: '', platforms: '' }); setNotice(''); }
  async function save() { setSaving(true); setError(''); setNotice(''); try { const response = await fetch('/api/library', { method: 'POST', headers: { 'Content-Type': 'application/json' }, body: JSON.stringify({ id: selected?.id, kind, ...form, tags: split(form.tags), platforms: split(form.platforms) }) }); const body = await response.json() as { error?: string }; if (!response.ok) throw new Error(body.error || 'Не вдалося зберегти матеріал.'); setNotice('Збережено.'); await load(); } catch (reason) { setError(reason instanceof Error ? reason.message : 'Не вдалося зберегти матеріал.'); } finally { setSaving(false); } }
  async function archive(item: Item) { if (!window.confirm(`Перемістити «${item.title}» в архів?`)) return; const response = await fetch('/api/library', { method: 'POST', headers: { 'Content-Type': 'application/json' }, body: JSON.stringify({ action: 'archive', id: item.id }) }); if (!response.ok) { const body = await response.json() as { error?: string }; setError(body.error || 'Не вдалося перемістити матеріал.'); return; } if (selected?.id === item.id) edit(null); await load(); }
  return <div className="library-workspace"><section className="library-hero"><div><p className="eyebrow">Єдине місце для робочих матеріалів</p><h2>Бібліотека</h2><p>Зберігай українські та російські версії оголошень, а також скрипти відповідей.</p></div><Button onClick={() => edit(null)}><FilePlus2 data-icon="inline-start" />Додати матеріал</Button></section>
    {error && <div className="workspace-error" role="alert">{error}</div>}{notice && <div className="reports-notice" role="status">{notice}</div>}
    <div className="library-toolbar"><div className="library-kind-picker" role="tablist" aria-label="Тип матеріалу">{(['advertisement','script'] as Kind[]).map((value) => <button type="button" role="tab" aria-selected={kind === value} key={value} onClick={() => { setKind(value); edit(null); }}>{kindLabels[value]}</button>)}</div><label className="library-search"><Search /><Input value={search} onChange={(event) => setSearch(event.target.value)} placeholder="Пошук за назвою або текстом…" /></label></div>
    <div className="library-layout"><section className="library-list">{loading ? <div className="workspace-loading">Завантаження…</div> : items.length ? items.map((item) => <button type="button" className={`library-item ${selected?.id === item.id ? 'is-selected' : ''}`} key={item.id} onClick={() => edit(item)}><span><strong>{item.title}</strong><small>{item.ukText || item.ruText}</small></span><Badge variant="outline">{item.kind === 'advertisement' ? 'Оголошення' : 'Скрипт'}</Badge></button>) : <div className="workspace-empty"><BookOpenText /><strong>Матеріалів ще немає</strong><p>Додай перше оголошення або скрипт.</p></div>}</section>
      <section className="library-editor">{selected || form.title ? <><div className="card-heading"><div><p className="eyebrow">Редактор</p><h3>{selected ? 'Редагувати матеріал' : `Нове: ${kindLabels[kind]}`}</h3></div>{selected && <Button variant="ghost" size="sm" onClick={() => void archive(selected)}><Archive data-icon="inline-start" />В архів</Button>}</div><label>Назва<Input value={form.title} onChange={(event) => setForm({ ...form, title: event.target.value })} placeholder="Наприклад: Англійська — батьки школярів" /></label><label>Українська версія<Textarea rows={7} value={form.ukText} onChange={(event) => setForm({ ...form, ukText: event.target.value })} placeholder="Текст українською…" /></label><label>Російська версія<Textarea rows={7} value={form.ruText} onChange={(event) => setForm({ ...form, ruText: event.target.value })} placeholder="Текст російською…" /></label><label>Нотатка<Textarea rows={3} value={form.notes} onChange={(event) => setForm({ ...form, notes: event.target.value })} placeholder="Коли та де використовувати…" /></label><div className="library-two-fields"><label>Теги<Input value={form.tags} onChange={(event) => setForm({ ...form, tags: event.target.value })} placeholder="школа, англійська" /></label><label>Платформи<Input value={form.platforms} onChange={(event) => setForm({ ...form, platforms: event.target.value })} placeholder="telegram, viber" /></label></div><Button onClick={() => void save()} disabled={saving || !form.title.trim() || (!form.ukText.trim() && !form.ruText.trim())}>{saving ? 'Зберігаємо…' : 'Зберегти'}</Button></> : <div className="workspace-empty"><BookOpenText /><strong>Обери матеріал</strong><p>Або натисни «Додати матеріал».</p></div>}</section></div></div>;
}
function split(value: string) { return value.split(',').map((item) => item.trim()).filter(Boolean); }
