'use client';

import { useEffect, useState } from 'react';
import { Button } from '@/components/ui/button';
import { Input } from '@/components/ui/input';
import { Dialog, DialogContent, DialogDescription, DialogHeader, DialogTitle } from '@/components/ui/dialog';

const DIRECTIONS = ['Англійська', 'Німецька', 'Польська', 'Математика', 'Шкільні предмети — комплексно', 'Логопедія та дефектологія', 'Малювання', 'ІТ та шахи'];

export function TodaySettingsDialog({ open, onClose, initialDirections, initialDailyGoal, initialMonthlyGoal, initialFunnelTargets, onSaved }: { open: boolean; onClose: () => void; initialDirections: string[]; initialDailyGoal: number; initialMonthlyGoal: number; initialFunnelTargets:{publicationRate:number;responseRate:number;bookingRate:number;completionRate:number}; onSaved: () => void }) {
  const [directions, setDirections] = useState<string[]>(initialDirections);
  const [daily, setDaily] = useState(String(initialDailyGoal));
  const [monthly, setMonthly] = useState(String(initialMonthlyGoal));
  const [rates,setRates]=useState(()=>({publicationRate:String(initialFunnelTargets.publicationRate),responseRate:String(initialFunnelTargets.responseRate),bookingRate:String(initialFunnelTargets.bookingRate),completionRate:String(initialFunnelTargets.completionRate)}));
  const [saving, setSaving] = useState(false); const [error, setError] = useState('');
  useEffect(() => { if (open) { setDirections(initialDirections); setDaily(String(initialDailyGoal)); setMonthly(String(initialMonthlyGoal)); setRates({publicationRate:String(initialFunnelTargets.publicationRate),responseRate:String(initialFunnelTargets.responseRate),bookingRate:String(initialFunnelTargets.bookingRate),completionRate:String(initialFunnelTargets.completionRate)}); setError(''); } }, [open, initialDirections, initialDailyGoal, initialMonthlyGoal, initialFunnelTargets]);

  async function save() { setSaving(true); setError(''); try { const response = await fetch('/api/settings', { method: 'POST', headers: { 'Content-Type': 'application/json' }, body: JSON.stringify({ settings: { focus_directions: directions, daily_booking_goal: Number(daily), monthly_booking_goal: Number(monthly), target_publication_rate:Number(rates.publicationRate), target_response_rate:Number(rates.responseRate), target_booking_rate:Number(rates.bookingRate), target_completion_rate:Number(rates.completionRate) } }) }); const body = await response.json() as { error?: string }; if (!response.ok) throw new Error(body.error || 'Не вдалося зберегти налаштування.'); onSaved(); onClose(); } catch (reason) { setError(reason instanceof Error ? reason.message : 'Не вдалося зберегти налаштування.'); } finally { setSaving(false); } }
  return <Dialog open={open} onOpenChange={(next) => { if (!next && !saving) onClose(); }}><DialogContent className="today-settings-dialog" showCloseButton={false}><DialogHeader><p className="eyebrow">Налаштування фокусу</p><DialogTitle>Цілі та напрямки</DialogTitle><DialogDescription>Налаштуй денну й місячну ціль та напрямки, які мають бути у фокусі Today.</DialogDescription></DialogHeader><div className="today-settings-fields"><label>Ціль записів на день<Input type="number" min="0" max="100000" value={daily} onChange={(event) => setDaily(event.target.value)} /></label><label>Ціль записів на місяць<Input type="number" min="0" max="100000" value={monthly} onChange={(event) => setMonthly(event.target.value)} /></label></div><fieldset><legend>Цільова конверсія воронки, %</legend><div className="today-settings-fields"><label>Публікація / приєднання<Input type="number" min="0" max="100" value={rates.publicationRate} onChange={(event)=>setRates({...rates,publicationRate:event.target.value})} /></label><label>Відгук / публікація<Input type="number" min="0" max="100" value={rates.responseRate} onChange={(event)=>setRates({...rates,responseRate:event.target.value})} /></label><label>Запис / відгук<Input type="number" min="0" max="100" value={rates.bookingRate} onChange={(event)=>setRates({...rates,bookingRate:event.target.value})} /></label><label>Проведено / запис<Input type="number" min="0" max="100" value={rates.completionRate} onChange={(event)=>setRates({...rates,completionRate:event.target.value})} /></label></div><p className="muted-note">0% означає, що ціль для цього етапу поки не задана.</p></fieldset><fieldset><legend>Фокус напрямків</legend><div className="direction-checks">{DIRECTIONS.map((direction) => <label key={direction}><input type="checkbox" checked={directions.includes(direction)} onChange={(event) => setDirections((current) => event.target.checked ? [...current, direction] : current.filter((item) => item !== direction))} />{direction}</label>)}</div></fieldset>{error && <p className="workspace-error" role="alert">{error}</p>}<div className="dialog-actions"><Button variant="outline" onClick={onClose}>Скасувати</Button><Button onClick={() => void save()} disabled={saving}>{saving ? 'Зберігаємо…' : 'Зберегти'}</Button></div></DialogContent></Dialog>;
}
